name: isoxml
description: A Dart library for interacting with ISO 11783-10 XML documents and the ISO 11783-11 Data Directory.
version: 1.0.0
repository: https://github.com/dudlileif/isoxml_dart
topics: [agriculture, iso-11783]

environment:
  sdk: ^3.0.0

dependencies:
  archive: ^3.4.10
  collection: ^1.18.0
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  xml: ^6.5.0
  xml_annotation: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.8  
  copy_with_extension_gen: ^5.0.4
  http: ^1.2.1
  test: ^1.24.0
  very_good_analysis: ^5.1.0
  xml_serializable: ^2.5.0
