name: isoxml_dart
description: A Dart library for interacting with ISO 11783-10 XML documents and the ISO 11783-11 Data Directory.
version: 0.1.0
repository: https://github.com/dudlileif/isoxml_dart
topics: [agriculture, isobus, iso-11783]

environment:
  sdk: ^3.6.0

dependencies:
  archive: ^4.0.2
  collection: ^1.19.0
  copy_with_extension: ^6.0.0
  equatable: ^2.0.7
  web: ^1.1.0
  xml: ^6.5.0
  xml_annotation: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.14
  copy_with_extension_gen: ^6.0.0
  http: ^1.2.2
  test: ^1.25.14
  very_good_analysis: ^7.0.0
  xml_serializable: ^2.5.3
