name: isoxml_dart
description: A Dart library for interacting with ISO 11783-10 XML documents and the ISO 11783-11 Data Directory.
version: 0.1.0
repository: https://github.com/dudlileif/isoxml_dart
topics: [agriculture, isobus, iso-11783]

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^4.0.7
  collection: ^1.19.0
  copy_with_extension: ^6.0.1
  equatable: ^2.0.7
  web: ^1.1.1
  xml: ^6.6.0
  xml_annotation: ^2.4.0

dev_dependencies:
  build_runner: ^2.5.4
  copy_with_extension_gen: ^6.0.1
  http: ^1.5.0
  test: ^1.26.3
  very_good_analysis: ^9.0.0
  xml_serializable: ^2.5.4
