name: Publish docs

on:
  push:
    branches:
      - main
    paths:
        - 'lib/**''
        - 'README.md'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get dependencies
        run: dart pub get

      - name: Build docs
        run: dart doc
            
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
            path: "doc/api"
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    