name: Code analysis and tests

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    paths:
      - '**/*.dart'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [vm, chrome]
    steps:
      - name: Clone repository 
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
          
      - name: Get dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format . --output=none --set-exit-if-changed

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test --platform ${{ matrix.platform }}
